2019-02-05 13:38:11,435 p=1420 u=devops |  ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to have been in '/home/devops/ansible_implementation/samba.yml': line 8, column 30, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    install_state: installed
    random_var: This is colon: test
                             ^ here

2019-02-05 13:50:17,850 p=1782 u=devops |  PLAY [create mail relay servers] *******************************************************************************************************************************************************************
2019-02-05 13:50:17,859 p=1782 u=devops |  TASK [Gathering Facts] *****************************************************************************************************************************************************************************
2019-02-05 13:50:20,654 p=1782 u=devops |  ok: [support1.2c70.internal]
2019-02-05 13:50:20,671 p=1782 u=devops |  TASK [install postfix package] *********************************************************************************************************************************************************************
2019-02-05 13:50:22,349 p=1782 u=devops |  ok: [support1.2c70.internal]
2019-02-05 13:50:22,366 p=1782 u=devops |  TASK [install mail config files] *******************************************************************************************************************************************************************
2019-02-05 13:50:22,951 p=1782 u=devops |  changed: [support1.2c70.internal]
2019-02-05 13:50:22,965 p=1782 u=devops |  TASK [check main.cf file] **************************************************************************************************************************************************************************
2019-02-05 13:50:23,484 p=1782 u=devops |  ok: [support1.2c70.internal]
2019-02-05 13:50:23,501 p=1782 u=devops |  TASK [verify main.cf file exists] ******************************************************************************************************************************************************************
2019-02-05 13:50:23,573 p=1782 u=devops |  ok: [support1.2c70.internal] => {
    "msg": "The main.cf file exists"
}
2019-02-05 13:50:23,592 p=1782 u=devops |  TASK [start and enable mail services] **************************************************************************************************************************************************************
2019-02-05 13:50:24,171 p=1782 u=devops |  ok: [support1.2c70.internal]
2019-02-05 13:50:24,190 p=1782 u=devops |  TASK [check for always_bcc] ************************************************************************************************************************************************************************
2019-02-05 13:50:24,742 p=1782 u=devops |  skipping: [support1.2c70.internal]
2019-02-05 13:50:24,758 p=1782 u=devops |  TASK [email notification of always_bcc config] *****************************************************************************************************************************************************
2019-02-05 13:50:24,780 p=1782 u=devops |  fatal: [support1.2c70.internal]: FAILED! => {"msg": "The conditional check 'bcc_state.stdout != 'always_bcc ='' failed. The error was: error while evaluating conditional (bcc_state.stdout != 'always_bcc ='): 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/home/devops/ansible_implementation/mailrelay.yml': line 40, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: email notification of always_bcc config\n      ^ here\n"}
2019-02-05 13:50:24,782 p=1782 u=devops |  RUNNING HANDLER [restart postfix] ******************************************************************************************************************************************************************
2019-02-05 13:50:24,784 p=1782 u=devops |  	to retry, use: --limit @/home/devops/ansible_implementation/mailrelay.retry

2019-02-05 13:50:24,784 p=1782 u=devops |  PLAY RECAP *****************************************************************************************************************************************************************************************
2019-02-05 13:50:24,784 p=1782 u=devops |  support1.2c70.internal     : ok=6    changed=1    unreachable=0    failed=1   
